package cn.javaer.wechat.sdk.pay.model;

import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link WeChatPayOrderQueryResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractWeChatPayOrderQueryResponseAssert<S extends AbstractWeChatPayOrderQueryResponseAssert<S, A>, A extends WeChatPayOrderQueryResponse> extends AbstractWeChatPayResponseAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractWeChatPayOrderQueryResponseAssert}</code> to make assertions on actual WeChatPayOrderQueryResponse.
   * @param actual the WeChatPayOrderQueryResponse we want to make assertions on.
   */
  protected AbstractWeChatPayOrderQueryResponseAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's attach is equal to the given one.
   * @param attach the given attach to compare the actual WeChatPayOrderQueryResponse's attach to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's attach is not equal to the given one.
   */
  public S hasAttach(String attach) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting attach of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualAttach = actual.getAttach();
    if (!Objects.areEqual(actualAttach, attach)) {
      failWithMessage(assertjErrorMessage, actual, attach, actualAttach);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's bankType is equal to the given one.
   * @param bankType the given bankType to compare the actual WeChatPayOrderQueryResponse's bankType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's bankType is not equal to the given one.
   */
  public S hasBankType(String bankType) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting bankType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualBankType = actual.getBankType();
    if (!Objects.areEqual(actualBankType, bankType)) {
      failWithMessage(assertjErrorMessage, actual, bankType, actualBankType);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's cashFee is equal to the given one.
   * @param cashFee the given cashFee to compare the actual WeChatPayOrderQueryResponse's cashFee to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's cashFee is not equal to the given one.
   */
  public S hasCashFee(Integer cashFee) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting cashFee of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualCashFee = actual.getCashFee();
    if (!Objects.areEqual(actualCashFee, cashFee)) {
      failWithMessage(assertjErrorMessage, actual, cashFee, actualCashFee);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's cashFeeType is equal to the given one.
   * @param cashFeeType the given cashFeeType to compare the actual WeChatPayOrderQueryResponse's cashFeeType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's cashFeeType is not equal to the given one.
   */
  public S hasCashFeeType(String cashFeeType) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting cashFeeType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualCashFeeType = actual.getCashFeeType();
    if (!Objects.areEqual(actualCashFeeType, cashFeeType)) {
      failWithMessage(assertjErrorMessage, actual, cashFeeType, actualCashFeeType);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's couponCount is equal to the given one.
   * @param couponCount the given couponCount to compare the actual WeChatPayOrderQueryResponse's couponCount to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's couponCount is not equal to the given one.
   */
  public S hasCouponCount(Integer couponCount) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting couponCount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualCouponCount = actual.getCouponCount();
    if (!Objects.areEqual(actualCouponCount, couponCount)) {
      failWithMessage(assertjErrorMessage, actual, couponCount, actualCouponCount);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's couponFee is equal to the given one.
   * @param couponFee the given couponFee to compare the actual WeChatPayOrderQueryResponse's couponFee to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's couponFee is not equal to the given one.
   */
  public S hasCouponFee(Integer couponFee) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting couponFee of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualCouponFee = actual.getCouponFee();
    if (!Objects.areEqual(actualCouponFee, couponFee)) {
      failWithMessage(assertjErrorMessage, actual, couponFee, actualCouponFee);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's coupons is equal to the given one.
   * @param coupons the given coupons to compare the actual WeChatPayOrderQueryResponse's coupons to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's coupons is not equal to the given one.
   */
  public S hasCoupons(java.util.Map coupons) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting coupons of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.util.Map actualCoupons = actual.getCoupons();
    if (!Objects.areEqual(actualCoupons, coupons)) {
      failWithMessage(assertjErrorMessage, actual, coupons, actualCoupons);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's detail is equal to the given one.
   * @param detail the given detail to compare the actual WeChatPayOrderQueryResponse's detail to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's detail is not equal to the given one.
   */
  public S hasDetail(String detail) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting detail of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualDetail = actual.getDetail();
    if (!Objects.areEqual(actualDetail, detail)) {
      failWithMessage(assertjErrorMessage, actual, detail, actualDetail);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's deviceInfo is equal to the given one.
   * @param deviceInfo the given deviceInfo to compare the actual WeChatPayOrderQueryResponse's deviceInfo to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's deviceInfo is not equal to the given one.
   */
  public S hasDeviceInfo(String deviceInfo) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting deviceInfo of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualDeviceInfo = actual.getDeviceInfo();
    if (!Objects.areEqual(actualDeviceInfo, deviceInfo)) {
      failWithMessage(assertjErrorMessage, actual, deviceInfo, actualDeviceInfo);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's feeType is equal to the given one.
   * @param feeType the given feeType to compare the actual WeChatPayOrderQueryResponse's feeType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's feeType is not equal to the given one.
   */
  public S hasFeeType(String feeType) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting feeType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualFeeType = actual.getFeeType();
    if (!Objects.areEqual(actualFeeType, feeType)) {
      failWithMessage(assertjErrorMessage, actual, feeType, actualFeeType);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's isSubscribe is equal to the given one.
   * @param isSubscribe the given isSubscribe to compare the actual WeChatPayOrderQueryResponse's isSubscribe to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's isSubscribe is not equal to the given one.
   */
  public S hasIsSubscribe(String isSubscribe) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting isSubscribe of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualIsSubscribe = actual.getIsSubscribe();
    if (!Objects.areEqual(actualIsSubscribe, isSubscribe)) {
      failWithMessage(assertjErrorMessage, actual, isSubscribe, actualIsSubscribe);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's openid is equal to the given one.
   * @param openid the given openid to compare the actual WeChatPayOrderQueryResponse's openid to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's openid is not equal to the given one.
   */
  public S hasOpenid(String openid) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting openid of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualOpenid = actual.getOpenid();
    if (!Objects.areEqual(actualOpenid, openid)) {
      failWithMessage(assertjErrorMessage, actual, openid, actualOpenid);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's outTradeNo is equal to the given one.
   * @param outTradeNo the given outTradeNo to compare the actual WeChatPayOrderQueryResponse's outTradeNo to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's outTradeNo is not equal to the given one.
   */
  public S hasOutTradeNo(String outTradeNo) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting outTradeNo of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualOutTradeNo = actual.getOutTradeNo();
    if (!Objects.areEqual(actualOutTradeNo, outTradeNo)) {
      failWithMessage(assertjErrorMessage, actual, outTradeNo, actualOutTradeNo);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's settlementTotalFee is equal to the given one.
   * @param settlementTotalFee the given settlementTotalFee to compare the actual WeChatPayOrderQueryResponse's settlementTotalFee to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's settlementTotalFee is not equal to the given one.
   */
  public S hasSettlementTotalFee(Integer settlementTotalFee) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting settlementTotalFee of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualSettlementTotalFee = actual.getSettlementTotalFee();
    if (!Objects.areEqual(actualSettlementTotalFee, settlementTotalFee)) {
      failWithMessage(assertjErrorMessage, actual, settlementTotalFee, actualSettlementTotalFee);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's subIsSubscribe is equal to the given one.
   * @param subIsSubscribe the given subIsSubscribe to compare the actual WeChatPayOrderQueryResponse's subIsSubscribe to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's subIsSubscribe is not equal to the given one.
   */
  public S hasSubIsSubscribe(String subIsSubscribe) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting subIsSubscribe of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualSubIsSubscribe = actual.getSubIsSubscribe();
    if (!Objects.areEqual(actualSubIsSubscribe, subIsSubscribe)) {
      failWithMessage(assertjErrorMessage, actual, subIsSubscribe, actualSubIsSubscribe);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's subOpenid is equal to the given one.
   * @param subOpenid the given subOpenid to compare the actual WeChatPayOrderQueryResponse's subOpenid to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's subOpenid is not equal to the given one.
   */
  public S hasSubOpenid(String subOpenid) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting subOpenid of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualSubOpenid = actual.getSubOpenid();
    if (!Objects.areEqual(actualSubOpenid, subOpenid)) {
      failWithMessage(assertjErrorMessage, actual, subOpenid, actualSubOpenid);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's timeEnd is equal to the given one.
   * @param timeEnd the given timeEnd to compare the actual WeChatPayOrderQueryResponse's timeEnd to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's timeEnd is not equal to the given one.
   */
  public S hasTimeEnd(String timeEnd) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting timeEnd of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTimeEnd = actual.getTimeEnd();
    if (!Objects.areEqual(actualTimeEnd, timeEnd)) {
      failWithMessage(assertjErrorMessage, actual, timeEnd, actualTimeEnd);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's totalFee is equal to the given one.
   * @param totalFee the given totalFee to compare the actual WeChatPayOrderQueryResponse's totalFee to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's totalFee is not equal to the given one.
   */
  public S hasTotalFee(Integer totalFee) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting totalFee of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualTotalFee = actual.getTotalFee();
    if (!Objects.areEqual(actualTotalFee, totalFee)) {
      failWithMessage(assertjErrorMessage, actual, totalFee, actualTotalFee);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's tradeState is equal to the given one.
   * @param tradeState the given tradeState to compare the actual WeChatPayOrderQueryResponse's tradeState to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's tradeState is not equal to the given one.
   */
  public S hasTradeState(String tradeState) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting tradeState of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTradeState = actual.getTradeState();
    if (!Objects.areEqual(actualTradeState, tradeState)) {
      failWithMessage(assertjErrorMessage, actual, tradeState, actualTradeState);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's tradeStateDesc is equal to the given one.
   * @param tradeStateDesc the given tradeStateDesc to compare the actual WeChatPayOrderQueryResponse's tradeStateDesc to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's tradeStateDesc is not equal to the given one.
   */
  public S hasTradeStateDesc(String tradeStateDesc) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting tradeStateDesc of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTradeStateDesc = actual.getTradeStateDesc();
    if (!Objects.areEqual(actualTradeStateDesc, tradeStateDesc)) {
      failWithMessage(assertjErrorMessage, actual, tradeStateDesc, actualTradeStateDesc);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's tradeType is equal to the given one.
   * @param tradeType the given tradeType to compare the actual WeChatPayOrderQueryResponse's tradeType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's tradeType is not equal to the given one.
   */
  public S hasTradeType(String tradeType) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting tradeType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTradeType = actual.getTradeType();
    if (!Objects.areEqual(actualTradeType, tradeType)) {
      failWithMessage(assertjErrorMessage, actual, tradeType, actualTradeType);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryResponse's transactionId is equal to the given one.
   * @param transactionId the given transactionId to compare the actual WeChatPayOrderQueryResponse's transactionId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryResponse's transactionId is not equal to the given one.
   */
  public S hasTransactionId(String transactionId) {
    // check that actual WeChatPayOrderQueryResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting transactionId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTransactionId = actual.getTransactionId();
    if (!Objects.areEqual(actualTransactionId, transactionId)) {
      failWithMessage(assertjErrorMessage, actual, transactionId, actualTransactionId);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
