package cn.javaer.wechat.sdk.pay.model;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link WeChatPayOrderQueryRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractWeChatPayOrderQueryRequestAssert<S extends AbstractWeChatPayOrderQueryRequestAssert<S, A>, A extends WeChatPayOrderQueryRequest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractWeChatPayOrderQueryRequestAssert}</code> to make assertions on actual WeChatPayOrderQueryRequest.
   * @param actual the WeChatPayOrderQueryRequest we want to make assertions on.
   */
  protected AbstractWeChatPayOrderQueryRequestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's appid is equal to the given one.
   * @param appid the given appid to compare the actual WeChatPayOrderQueryRequest's appid to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's appid is not equal to the given one.
   */
  public S hasAppid(String appid) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting appid of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualAppid = actual.getAppid();
    if (!Objects.areEqual(actualAppid, appid)) {
      failWithMessage(assertjErrorMessage, actual, appid, actualAppid);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's mchId is equal to the given one.
   * @param mchId the given mchId to compare the actual WeChatPayOrderQueryRequest's mchId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's mchId is not equal to the given one.
   */
  public S hasMchId(String mchId) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting mchId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualMchId = actual.getMchId();
    if (!Objects.areEqual(actualMchId, mchId)) {
      failWithMessage(assertjErrorMessage, actual, mchId, actualMchId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's nonceStr is equal to the given one.
   * @param nonceStr the given nonceStr to compare the actual WeChatPayOrderQueryRequest's nonceStr to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's nonceStr is not equal to the given one.
   */
  public S hasNonceStr(String nonceStr) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nonceStr of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualNonceStr = actual.getNonceStr();
    if (!Objects.areEqual(actualNonceStr, nonceStr)) {
      failWithMessage(assertjErrorMessage, actual, nonceStr, actualNonceStr);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's outTradeNo is equal to the given one.
   * @param outTradeNo the given outTradeNo to compare the actual WeChatPayOrderQueryRequest's outTradeNo to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's outTradeNo is not equal to the given one.
   */
  public S hasOutTradeNo(String outTradeNo) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting outTradeNo of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualOutTradeNo = actual.getOutTradeNo();
    if (!Objects.areEqual(actualOutTradeNo, outTradeNo)) {
      failWithMessage(assertjErrorMessage, actual, outTradeNo, actualOutTradeNo);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's sign is equal to the given one.
   * @param sign the given sign to compare the actual WeChatPayOrderQueryRequest's sign to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's sign is not equal to the given one.
   */
  public S hasSign(String sign) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting sign of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualSign = actual.getSign();
    if (!Objects.areEqual(actualSign, sign)) {
      failWithMessage(assertjErrorMessage, actual, sign, actualSign);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayOrderQueryRequest's transactionId is equal to the given one.
   * @param transactionId the given transactionId to compare the actual WeChatPayOrderQueryRequest's transactionId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayOrderQueryRequest's transactionId is not equal to the given one.
   */
  public S hasTransactionId(String transactionId) {
    // check that actual WeChatPayOrderQueryRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting transactionId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualTransactionId = actual.getTransactionId();
    if (!Objects.areEqual(actualTransactionId, transactionId)) {
      failWithMessage(assertjErrorMessage, actual, transactionId, actualTransactionId);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
