package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link AbstractWeChatPayResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAbstractWeChatPayResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AbstractWeChatPayResponseAssert extends AbstractAbstractWeChatPayResponseAssert<AbstractWeChatPayResponseAssert, AbstractWeChatPayResponse> {

  /**
   * Creates a new <code>{@link AbstractWeChatPayResponseAssert}</code> to make assertions on actual AbstractWeChatPayResponse.
   * @param actual the AbstractWeChatPayResponse we want to make assertions on.
   */
  public AbstractWeChatPayResponseAssert(AbstractWeChatPayResponse actual) {
    super(actual, AbstractWeChatPayResponseAssert.class);
  }

  /**
   * An entry point for AbstractWeChatPayResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAbstractWeChatPayResponse)</code> and get specific assertion with code completion.
   * @param actual the AbstractWeChatPayResponse we want to make assertions on.
   * @return a new <code>{@link AbstractWeChatPayResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AbstractWeChatPayResponseAssert assertThat(AbstractWeChatPayResponse actual) {
    return new AbstractWeChatPayResponseAssert(actual);
  }
}
