package cn.javaer.wechat.sdk.pay.model;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link WeChatPayRequest} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractWeChatPayRequestAssert<S extends AbstractWeChatPayRequestAssert<S, A>, A extends WeChatPayRequest> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractWeChatPayRequestAssert}</code> to make assertions on actual WeChatPayRequest.
   * @param actual the WeChatPayRequest we want to make assertions on.
   */
  protected AbstractWeChatPayRequestAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual WeChatPayRequest's appid is equal to the given one.
   * @param appid the given appid to compare the actual WeChatPayRequest's appid to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayRequest's appid is not equal to the given one.
   */
  public S hasAppid(String appid) {
    // check that actual WeChatPayRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting appid of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualAppid = actual.getAppid();
    if (!Objects.areEqual(actualAppid, appid)) {
      failWithMessage(assertjErrorMessage, actual, appid, actualAppid);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayRequest's mchId is equal to the given one.
   * @param mchId the given mchId to compare the actual WeChatPayRequest's mchId to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayRequest's mchId is not equal to the given one.
   */
  public S hasMchId(String mchId) {
    // check that actual WeChatPayRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting mchId of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualMchId = actual.getMchId();
    if (!Objects.areEqual(actualMchId, mchId)) {
      failWithMessage(assertjErrorMessage, actual, mchId, actualMchId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayRequest's nonceStr is equal to the given one.
   * @param nonceStr the given nonceStr to compare the actual WeChatPayRequest's nonceStr to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayRequest's nonceStr is not equal to the given one.
   */
  public S hasNonceStr(String nonceStr) {
    // check that actual WeChatPayRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting nonceStr of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualNonceStr = actual.getNonceStr();
    if (!Objects.areEqual(actualNonceStr, nonceStr)) {
      failWithMessage(assertjErrorMessage, actual, nonceStr, actualNonceStr);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayRequest's sign is equal to the given one.
   * @param sign the given sign to compare the actual WeChatPayRequest's sign to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayRequest's sign is not equal to the given one.
   */
  public S hasSign(String sign) {
    // check that actual WeChatPayRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting sign of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualSign = actual.getSign();
    if (!Objects.areEqual(actualSign, sign)) {
      failWithMessage(assertjErrorMessage, actual, sign, actualSign);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual WeChatPayRequest's signType is equal to the given one.
   * @param signType the given signType to compare the actual WeChatPayRequest's signType to.
   * @return this assertion object.
   * @throws AssertionError - if the actual WeChatPayRequest's signType is not equal to the given one.
   */
  public S hasSignType(String signType) {
    // check that actual WeChatPayRequest we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting signType of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualSignType = actual.getSignType();
    if (!Objects.areEqual(actualSignType, signType)) {
      failWithMessage(assertjErrorMessage, actual, signType, actualSignType);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
