package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayCoupon} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayCouponAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayCouponAssert extends AbstractWeChatPayCouponAssert<WeChatPayCouponAssert, WeChatPayCoupon> {

  /**
   * Creates a new <code>{@link WeChatPayCouponAssert}</code> to make assertions on actual WeChatPayCoupon.
   * @param actual the WeChatPayCoupon we want to make assertions on.
   */
  public WeChatPayCouponAssert(WeChatPayCoupon actual) {
    super(actual, WeChatPayCouponAssert.class);
  }

  /**
   * An entry point for WeChatPayCouponAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayCoupon)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayCoupon we want to make assertions on.
   * @return a new <code>{@link WeChatPayCouponAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayCouponAssert assertThat(WeChatPayCoupon actual) {
    return new WeChatPayCouponAssert(actual);
  }
}
