package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayNotifyResult} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayNotifyResultAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayNotifyResultAssert extends AbstractWeChatPayNotifyResultAssert<WeChatPayNotifyResultAssert, WeChatPayNotifyResult> {

  /**
   * Creates a new <code>{@link WeChatPayNotifyResultAssert}</code> to make assertions on actual WeChatPayNotifyResult.
   * @param actual the WeChatPayNotifyResult we want to make assertions on.
   */
  public WeChatPayNotifyResultAssert(WeChatPayNotifyResult actual) {
    super(actual, WeChatPayNotifyResultAssert.class);
  }

  /**
   * An entry point for WeChatPayNotifyResultAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayNotifyResult)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayNotifyResult we want to make assertions on.
   * @return a new <code>{@link WeChatPayNotifyResultAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayNotifyResultAssert assertThat(WeChatPayNotifyResult actual) {
    return new WeChatPayNotifyResultAssert(actual);
  }
}
