package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatRefund} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatRefundAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatRefundAssert extends AbstractWeChatRefundAssert<WeChatRefundAssert, WeChatRefund> {

  /**
   * Creates a new <code>{@link WeChatRefundAssert}</code> to make assertions on actual WeChatRefund.
   * @param actual the WeChatRefund we want to make assertions on.
   */
  public WeChatRefundAssert(WeChatRefund actual) {
    super(actual, WeChatRefundAssert.class);
  }

  /**
   * An entry point for WeChatRefundAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatRefund)</code> and get specific assertion with code completion.
   * @param actual the WeChatRefund we want to make assertions on.
   * @return a new <code>{@link WeChatRefundAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatRefundAssert assertThat(WeChatRefund actual) {
    return new WeChatRefundAssert(actual);
  }
}
