package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayUnifiedOrderResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayUnifiedOrderResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayUnifiedOrderResponseAssert extends AbstractWeChatPayUnifiedOrderResponseAssert<WeChatPayUnifiedOrderResponseAssert, WeChatPayUnifiedOrderResponse> {

  /**
   * Creates a new <code>{@link WeChatPayUnifiedOrderResponseAssert}</code> to make assertions on actual WeChatPayUnifiedOrderResponse.
   * @param actual the WeChatPayUnifiedOrderResponse we want to make assertions on.
   */
  public WeChatPayUnifiedOrderResponseAssert(WeChatPayUnifiedOrderResponse actual) {
    super(actual, WeChatPayUnifiedOrderResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayUnifiedOrderResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayUnifiedOrderResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayUnifiedOrderResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayUnifiedOrderResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayUnifiedOrderResponseAssert assertThat(WeChatPayUnifiedOrderResponse actual) {
    return new WeChatPayUnifiedOrderResponseAssert(actual);
  }
}
