package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayUnifiedOrderRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayUnifiedOrderRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayUnifiedOrderRequestAssert extends AbstractWeChatPayUnifiedOrderRequestAssert<WeChatPayUnifiedOrderRequestAssert, WeChatPayUnifiedOrderRequest> {

  /**
   * Creates a new <code>{@link WeChatPayUnifiedOrderRequestAssert}</code> to make assertions on actual WeChatPayUnifiedOrderRequest.
   * @param actual the WeChatPayUnifiedOrderRequest we want to make assertions on.
   */
  public WeChatPayUnifiedOrderRequestAssert(WeChatPayUnifiedOrderRequest actual) {
    super(actual, WeChatPayUnifiedOrderRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayUnifiedOrderRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayUnifiedOrderRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayUnifiedOrderRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayUnifiedOrderRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayUnifiedOrderRequestAssert assertThat(WeChatPayUnifiedOrderRequest actual) {
    return new WeChatPayUnifiedOrderRequestAssert(actual);
  }
}
