package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayResponseAssert extends AbstractWeChatPayResponseAssert<WeChatPayResponseAssert, WeChatPayResponse> {

  /**
   * Creates a new <code>{@link WeChatPayResponseAssert}</code> to make assertions on actual WeChatPayResponse.
   * @param actual the WeChatPayResponse we want to make assertions on.
   */
  public WeChatPayResponseAssert(WeChatPayResponse actual) {
    super(actual, WeChatPayResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayResponseAssert assertThat(WeChatPayResponse actual) {
    return new WeChatPayResponseAssert(actual);
  }
}
