package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayCloseOrderRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayCloseOrderRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayCloseOrderRequestAssert extends AbstractWeChatPayCloseOrderRequestAssert<WeChatPayCloseOrderRequestAssert, WeChatPayCloseOrderRequest> {

  /**
   * Creates a new <code>{@link WeChatPayCloseOrderRequestAssert}</code> to make assertions on actual WeChatPayCloseOrderRequest.
   * @param actual the WeChatPayCloseOrderRequest we want to make assertions on.
   */
  public WeChatPayCloseOrderRequestAssert(WeChatPayCloseOrderRequest actual) {
    super(actual, WeChatPayCloseOrderRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayCloseOrderRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayCloseOrderRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayCloseOrderRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayCloseOrderRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayCloseOrderRequestAssert assertThat(WeChatPayCloseOrderRequest actual) {
    return new WeChatPayCloseOrderRequestAssert(actual);
  }
}
