package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayRefundQueryResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayRefundQueryResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayRefundQueryResponseAssert extends AbstractWeChatPayRefundQueryResponseAssert<WeChatPayRefundQueryResponseAssert, WeChatPayRefundQueryResponse> {

  /**
   * Creates a new <code>{@link WeChatPayRefundQueryResponseAssert}</code> to make assertions on actual WeChatPayRefundQueryResponse.
   * @param actual the WeChatPayRefundQueryResponse we want to make assertions on.
   */
  public WeChatPayRefundQueryResponseAssert(WeChatPayRefundQueryResponse actual) {
    super(actual, WeChatPayRefundQueryResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayRefundQueryResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayRefundQueryResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayRefundQueryResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayRefundQueryResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayRefundQueryResponseAssert assertThat(WeChatPayRefundQueryResponse actual) {
    return new WeChatPayRefundQueryResponseAssert(actual);
  }
}
