package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayNotifyResultResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayNotifyResultResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayNotifyResultResponseAssert extends AbstractWeChatPayNotifyResultResponseAssert<WeChatPayNotifyResultResponseAssert, WeChatPayNotifyResultResponse> {

  /**
   * Creates a new <code>{@link WeChatPayNotifyResultResponseAssert}</code> to make assertions on actual WeChatPayNotifyResultResponse.
   * @param actual the WeChatPayNotifyResultResponse we want to make assertions on.
   */
  public WeChatPayNotifyResultResponseAssert(WeChatPayNotifyResultResponse actual) {
    super(actual, WeChatPayNotifyResultResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayNotifyResultResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayNotifyResultResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayNotifyResultResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayNotifyResultResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayNotifyResultResponseAssert assertThat(WeChatPayNotifyResultResponse actual) {
    return new WeChatPayNotifyResultResponseAssert(actual);
  }
}
