package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayRefundRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayRefundRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayRefundRequestAssert extends AbstractWeChatPayRefundRequestAssert<WeChatPayRefundRequestAssert, WeChatPayRefundRequest> {

  /**
   * Creates a new <code>{@link WeChatPayRefundRequestAssert}</code> to make assertions on actual WeChatPayRefundRequest.
   * @param actual the WeChatPayRefundRequest we want to make assertions on.
   */
  public WeChatPayRefundRequestAssert(WeChatPayRefundRequest actual) {
    super(actual, WeChatPayRefundRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayRefundRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayRefundRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayRefundRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayRefundRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayRefundRequestAssert assertThat(WeChatPayRefundRequest actual) {
    return new WeChatPayRefundRequestAssert(actual);
  }
}
