package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayRefundResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayRefundResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayRefundResponseAssert extends AbstractWeChatPayRefundResponseAssert<WeChatPayRefundResponseAssert, WeChatPayRefundResponse> {

  /**
   * Creates a new <code>{@link WeChatPayRefundResponseAssert}</code> to make assertions on actual WeChatPayRefundResponse.
   * @param actual the WeChatPayRefundResponse we want to make assertions on.
   */
  public WeChatPayRefundResponseAssert(WeChatPayRefundResponse actual) {
    super(actual, WeChatPayRefundResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayRefundResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayRefundResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayRefundResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayRefundResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayRefundResponseAssert assertThat(WeChatPayRefundResponse actual) {
    return new WeChatPayRefundResponseAssert(actual);
  }
}
