package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayCloseOrderResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayCloseOrderResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayCloseOrderResponseAssert extends AbstractWeChatPayCloseOrderResponseAssert<WeChatPayCloseOrderResponseAssert, WeChatPayCloseOrderResponse> {

  /**
   * Creates a new <code>{@link WeChatPayCloseOrderResponseAssert}</code> to make assertions on actual WeChatPayCloseOrderResponse.
   * @param actual the WeChatPayCloseOrderResponse we want to make assertions on.
   */
  public WeChatPayCloseOrderResponseAssert(WeChatPayCloseOrderResponse actual) {
    super(actual, WeChatPayCloseOrderResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayCloseOrderResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayCloseOrderResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayCloseOrderResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayCloseOrderResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayCloseOrderResponseAssert assertThat(WeChatPayCloseOrderResponse actual) {
    return new WeChatPayCloseOrderResponseAssert(actual);
  }
}
