package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayOrderQueryResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayOrderQueryResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayOrderQueryResponseAssert extends AbstractWeChatPayOrderQueryResponseAssert<WeChatPayOrderQueryResponseAssert, WeChatPayOrderQueryResponse> {

  /**
   * Creates a new <code>{@link WeChatPayOrderQueryResponseAssert}</code> to make assertions on actual WeChatPayOrderQueryResponse.
   * @param actual the WeChatPayOrderQueryResponse we want to make assertions on.
   */
  public WeChatPayOrderQueryResponseAssert(WeChatPayOrderQueryResponse actual) {
    super(actual, WeChatPayOrderQueryResponseAssert.class);
  }

  /**
   * An entry point for WeChatPayOrderQueryResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayOrderQueryResponse)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayOrderQueryResponse we want to make assertions on.
   * @return a new <code>{@link WeChatPayOrderQueryResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayOrderQueryResponseAssert assertThat(WeChatPayOrderQueryResponse actual) {
    return new WeChatPayOrderQueryResponseAssert(actual);
  }
}
