package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayRequestAssert extends AbstractWeChatPayRequestAssert<WeChatPayRequestAssert, WeChatPayRequest> {

  /**
   * Creates a new <code>{@link WeChatPayRequestAssert}</code> to make assertions on actual WeChatPayRequest.
   * @param actual the WeChatPayRequest we want to make assertions on.
   */
  public WeChatPayRequestAssert(WeChatPayRequest actual) {
    super(actual, WeChatPayRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayRequestAssert assertThat(WeChatPayRequest actual) {
    return new WeChatPayRequestAssert(actual);
  }
}
