package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayOrderQueryRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayOrderQueryRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayOrderQueryRequestAssert extends AbstractWeChatPayOrderQueryRequestAssert<WeChatPayOrderQueryRequestAssert, WeChatPayOrderQueryRequest> {

  /**
   * Creates a new <code>{@link WeChatPayOrderQueryRequestAssert}</code> to make assertions on actual WeChatPayOrderQueryRequest.
   * @param actual the WeChatPayOrderQueryRequest we want to make assertions on.
   */
  public WeChatPayOrderQueryRequestAssert(WeChatPayOrderQueryRequest actual) {
    super(actual, WeChatPayOrderQueryRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayOrderQueryRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayOrderQueryRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayOrderQueryRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayOrderQueryRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayOrderQueryRequestAssert assertThat(WeChatPayOrderQueryRequest actual) {
    return new WeChatPayOrderQueryRequestAssert(actual);
  }
}
