package cn.javaer.wechat.sdk.pay.model;

/**
 * {@link WeChatPayRefundQueryRequest} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractWeChatPayRefundQueryRequestAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class WeChatPayRefundQueryRequestAssert extends AbstractWeChatPayRefundQueryRequestAssert<WeChatPayRefundQueryRequestAssert, WeChatPayRefundQueryRequest> {

  /**
   * Creates a new <code>{@link WeChatPayRefundQueryRequestAssert}</code> to make assertions on actual WeChatPayRefundQueryRequest.
   * @param actual the WeChatPayRefundQueryRequest we want to make assertions on.
   */
  public WeChatPayRefundQueryRequestAssert(WeChatPayRefundQueryRequest actual) {
    super(actual, WeChatPayRefundQueryRequestAssert.class);
  }

  /**
   * An entry point for WeChatPayRefundQueryRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myWeChatPayRefundQueryRequest)</code> and get specific assertion with code completion.
   * @param actual the WeChatPayRefundQueryRequest we want to make assertions on.
   * @return a new <code>{@link WeChatPayRefundQueryRequestAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static WeChatPayRefundQueryRequestAssert assertThat(WeChatPayRefundQueryRequest actual) {
    return new WeChatPayRefundQueryRequestAssert(actual);
  }
}
